[project]
name = "splitpdf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pdf2image>=1.17.0",
    "requests>=2.32.5",
    "typer>=0.23.2",
]

[tool.uv]
package = true

[dependency-groups]
dev = [
    "ruff>=0.15.8",
]

[project.scripts]
splitpdf = "splitpdf.main:app"
