[project]
name = "splitpdf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.135.2",
    "pdf2image>=1.17.0",
    "python-dotenv>=1.2.2",
    "requests>=2.32.5",
    "s3path>=0.6.5",
    "together>=2.7.0",
    "tqdm>=4.67.3",
    "typer>=0.23.2",
    "uvicorn>=0.42.0",
    "weaviate-client[agents]>=4.20.4",
]

[tool.uv]
package = true

[dependency-groups]
dev = [
    "ruff>=0.15.8",
]

[project.scripts]
altnl = "splitpdf.main:app"
